# SPDX-License-Identifier: (Apache-2.0)

XDP_TARGETS := sockex1_kern
USER_TARGETS := sockex1_user

COMMON_DIR = ../common
USER_LIBS = -lz

include $(COMMON_DIR)/common.mk
#COMMON_OBJS := $(COMMON_DIR)/common_params.o
