# SPDX-License-Identifier: (Apache-2.0)

XDP_TARGETS := xdp_fwd_kern
USER_TARGETS := xdp_fwd_user

COMMON_DIR = ../common
USER_LIBS = -pthread

include $(COMMON_DIR)/common.mk
#COMMON_OBJS := $(COMMON_DIR)/common_params.o
